# Generated by Django 3.1.7 on 2021-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210509_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Principal',
            field=models.CharField(default='Principal', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_of_school',
            field=models.CharField(default='City', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.CharField(default='manager', max_length=20),
        ),
    ]
